hparams = [
    {
        "model": "AICare",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 64,
        "output_dim": 1,
    },
    {
        "model": "MCGRU",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "RETAIN",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AdaCare",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "MCGRU",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "RETAIN",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AdaCare",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "MCGRU",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "RETAIN",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AdaCare",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "MCGRU",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "RETAIN",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
]

hparams_v2 = [
    {
        "model": "AICare",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "M3Care",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "GRU",
        "dataset": "esrd",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 0,
        "lab_dim": 17,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AICare",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "M3Care",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "GRU",
        "dataset": "cdsl",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 97,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AICare",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "M3Care",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "GRU",
        "dataset": "mimic-iv",
        "task": "outcome",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "AICare",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "M3Care",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
    {
        "model": "GRU",
        "dataset": "mimic-iv",
        "task": "readmission",
        "main_metric": "auprc",
        "patience": 10,
        "epochs": 50,
        "batch_size": 128,
        "learning_rate": 0.001,
        "demo_dim": 2,
        "lab_dim": 59,
        "hidden_dim": 128,
        "output_dim": 1,
    },
]
